[discord.filterclub]
AutoWebhooks=true
PreserveThreading=true
RemoteNickFormat="{NICK}\n"
Server="826451327768592415"
ShowEmbeds=true
ShowJoinPart=false
ShowTopicChange=false
SyncTopic=false
Token="DISCORD_BOT_TOKEN_PLACEHOLDER"
UseLocalAvatar=["telegram.daralo"]

[telegram.daralo]
DisableWebPagePreview=false
MessageFormat="MarkdownV2"
PreserveThreading=true
QuoteFormat="{MESSAGE}\n>>> {QUOTEMESSAGE}"
RemoteNickFormat="*{NICK}*\n"
ShowJoinPart=false
ShowTopicChange=false
Token="TELEGRAM_BOT_TOKEN_PLACEHOLDER"
UseFullName=true

[general]
MediaDownloadSize=10000000

[[gateway]]
name="fc--daralo"
enable=true

[[gateway.inout]]
account="discord.filterclub"
channel="ID:826480151796776971"

[[gateway.inout]]
account="telegram.daralo"
channel="-1001056923914"
