[discord.filterclub]
Token="DISCORD_BOT_TOKEN_PLACEHOLDER"
Server="826451327768592415"
AutoWebhooks=true
UseLocalAvatar=["telegram.daralo"]
ShowJoinPart=false
ShowTopicChange=false
ShowEmbeds=true
SyncTopic=false
PreserveThreading=true

[telegram.daralo]
Token="TELEGRAM_BOT_TOKEN_PLACEHOLDER"
MessageFormat="MarkdownV2"
QuoteFormat="{MESSAGE}\n>>> {QUOTEMESSAGE}"
DisableWebPagePreview=false
UseFullName=true
ShowJoinPart=false
ShowTopicChange=false
PreserveThreading=true

[general]
RemoteNickFormat="*{NICK}* \n"
MediaDownloadSize=10000000

[[gateway]]
name="fc--daralo"
enable=true

[[gateway.inout]]
account="discord.filterclub"
channel="ID:826480151796776971"

[[gateway.inout]]
account="telegram.daralo"
channel="-1001056923914"
