[discord.filterclub]
Token="DISCORD_BOT_TOKEN_PLACEHOLDER"
Server="826451327768592415"
AutoWebhooks=true
UseLocalAvatar=["telegram.daralo"]
ShowEmbeds=true

[telegram.daralo]
Token="TELEGRAM_BOT_TOKEN_PLACEHOLDER"
RemoteNickFormat="<b>{NICK}</b>\n"
MessageFormat="HTML"
QuoteFormat="{MESSAGE}\n\n>>> *{QUOTENICK}*\n{QUOTEMESSAGE}"
DisableWebPagePreview=false
UseFullName=true

[general]
RemoteNickFormat="{NICK}"
MediaDownloadSize=10000000

[[gateway]]
name="fc--daralo"
enable=true

[[gateway.inout]]
account="discord.filterclub"
channel="ID:826480151796776971"

[[gateway.inout]]
account="telegram.daralo"
channel="-1001056923914"
