[discord.filterclub]
Token="DISCORD_BOT_TOKEN_PLACEHOLDER"
Server="826451327768592415"
AutoWebhooks=true

[slack.filterclub-hu]
Token="SLACK_BOT_TOKEN_PLACEHOLDER"

[telegram.daralo]
Token="TELEGRAM_BOT_TOKEN_PLACEHOLDER"
RemoteNickFormat="<b>{NICK}</b>\n"
MessageFormat="HTML"
QuoteFormat="{MESSAGE}\n\n\n>>> *{QUOTENICK}*\n{QUOTEMESSAGE}"

[general]
RemoteNickFormat="{NICK}"
MediaDownloadSize=10000000


[[gateway]]
name="fc-hu-beans"
enable=true

[[gateway.inout]]
account="slack.filterclub-hu"
channel="ID:C8W0RUY1K"

[[gateway.inout]]
account="discord.filterclub"
channel="ID:826479740470034503"


[[gateway]]
name="fc-hu-brewing"
enable=true

[[gateway.inout]]
account="slack.filterclub-hu"
channel="ID:C8UA54M96"

[[gateway.inout]]
account="discord.filterclub"
channel="ID:826869293144080430"


[[gateway]]
name="fc-hu-gadgets"
enable=true

[[gateway.inout]]
account="slack.filterclub-hu"
channel="ID:C8UV7RN0J"

[[gateway.inout]]
account="discord.filterclub"
channel="ID:826479796749336616"


[[gateway]]
name="fc-hu-places"
enable=true

[[gateway.inout]]
account="slack.filterclub-hu"
channel="ID:C8YKMER7C"

[[gateway.inout]]
account="discord.filterclub"
channel="ID:826479822913404978"


[[gateway]]
name="fc-hu-people"
enable=true

[[gateway.inout]]
account="slack.filterclub-hu"
channel="ID:CBE0WRU9K"

[[gateway.inout]]
account="discord.filterclub"
channel="ID:828947762850562068"


[[gateway]]
name="fc-hu-events"
enable=true

[[gateway.inout]]
account="slack.filterclub-hu"
channel="ID:C8VP5REAJ"

[[gateway.inout]]
account="discord.filterclub"
channel="ID:826479771424260096"


[[gateway]]
name="fc-hu-orders"
enable=true

[[gateway.inout]]
account="slack.filterclub-hu"
channel="ID:C8USDD3A7"

[[gateway.inout]]
account="discord.filterclub"
channel="ID:826535759166439456"


[[gateway]]
name="fc-hu-random"
enable=true

[[gateway.inout]]
account="slack.filterclub-hu"
channel="ID:C8UN5E91R"

[[gateway.inout]]
account="discord.filterclub"
channel="ID:826480112580952115"


[[gateway]]
name="fc-hu-market"
enable=true

[[gateway.inout]]
account="slack.filterclub-hu"
channel="ID:CD1KP9YTT"

[[gateway.inout]]
account="discord.filterclub"
channel="ID:826535122139742238"


[[gateway]]
name="fc-hu-news"
enable=true

[[gateway.inout]]
account="slack.filterclub-hu"
channel="ID:C8VSUEWK1"

[[gateway.inout]]
account="discord.filterclub"
channel="ID:829116647968210944"


[[gateway]]
name="fc--daralo"
enable=true

[[gateway.inout]]
account="discord.filterclub"
channel="ID:826480151796776971"

[[gateway.inout]]
account="telegram.daralo"
channel="-1001056923914"

[[gateway.inout]]
account="slack.filterclub-hu"
channel="ID:CJ90WQ3TR"
