name: CI
on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Matterbridge config file
        run: |
          sed -i -- 's/DISCORD_BOT_TOKEN_PLACEHOLDER/${{ secrets.DISCORD_BOT_TOKEN }}/g' ${{ github.workspace }}/matterbridge/matterbridge.toml
          sed -i -- 's/SLACK_BOT_TOKEN_PLACEHOLDER/${{ secrets.SLACK_BOT_TOKEN }}/g' ${{ github.workspace }}/matterbridge/matterbridge.toml
          sed -i -- 's/TELEGRAM_BOT_TOKEN_PLACEHOLDER/${{ secrets.TELEGRAM_BOT_TOKEN }}/g' ${{ github.workspace }}/matterbridge/matterbridge.toml      
      - name: Configure SSH to server
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SERVER_PRIVATE_KEY }}" > ~/.ssh/server.key
          chmod 600 ~/.ssh/server.key
          cat >>~/.ssh/config <<END
          Host server
            User ${{ secrets.SERVER_USER }}
            HostName ${{ secrets.SERVER_HOST }}
            Port ${{ secrets.SERVER_PORT }}
            IdentityFile ~/.ssh/server.key
            StrictHostKeyChecking no
          END
      - name: Copy files over to server
        run: scp -r ${{ github.workspace }} server:/~
