name: CI
on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Matterbridge config file
        run: |
          sed -i -- 's/DISCORD_BOT_TOKEN_PLACEHOLDER/${{ secrets.DISCORD_BOT_TOKEN }}/g' ${{ github.workspace }}/matterbridge/matterbridge.toml
          sed -i -- 's/SLACK_BOT_TOKEN_PLACEHOLDER/${{ secrets.SLACK_BOT_TOKEN }}/g' ${{ github.workspace }}/matterbridge/matterbridge.toml
          sed -i -- 's/TELEGRAM_BOT_TOKEN_PLACEHOLDER/${{ secrets.TELEGRAM_BOT_TOKEN }}/g' ${{ github.workspace }}/matterbridge/matterbridge.toml      
      - name: Remove .git from repo directory
        run: rm -rf ${{ github.workspace }}/.git
      - name: Configure SSH to server
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SERVER_PRIVATE_KEY }}" > ~/.ssh/server.key
          chmod 600 ~/.ssh/server.key
          cat >>~/.ssh/config <<END
          Host server
            User ${{ secrets.SERVER_USER }}
            HostName ${{ secrets.SERVER_HOST }}
            Port ${{ secrets.SERVER_PORT }}
            IdentityFile ~/.ssh/server.key
            StrictHostKeyChecking no
          END
      - name: Stop service
        run: ssh server 'if [ /srv/@filterclub/ms-laurina/docker-compose top | grep matterbridge ]; then /srv/@filterclub/ms-laurina/docker-compose down -v; fi'
      - name: Copy files over to server
        run: scp -prq ${{ github.workspace }} server:/srv/@filterclub/
      - name: Start service
        run: ssh server 'cd /srv/@filterclub/ms-laurina/ && docker-compose up -d'
